### ISSUE TITLE
You can't use anything from iBlooket.github.io.

### ISSUE THREAD

**Issue by VillainsRule4000** [BlooketTools/blooktubers#1]
It was taken down. You can use the channels, but NOT the site format.

**Comment by v8f** [comment]
ok but like



this is just blookets button design and everything else . literally the offical blooket design.

**Comment by VillainsRule4000** [comment]
Still, it's an EXACT COPY, and wat wants me to take mine down. Wat does have a right to ask that, so I do to you. You don't even credit my site.

**Comment by v8f** [comment]
I'm not trying to use the site format. I had to manually change the style myself. I know I copied it but I changed the style (css) up a bit.

**Comment by v8f** [comment]
I also am just using wats site design.

**Comment by v8f** [comment]
I did take the design from the iblooket thing but really you just used blookets webpage style or wats so it dosent really matter at the end. Im basically not really even using i blookets design since i dont think you edited it or anythin. :\
